config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/intructions'
  get 'help' => 'static_pages#help'
  get 'about'=>'static_pages#about'
  devise_for :users
  authenticate :user do
    root to: "static_pages#home"
    get 'home' => 'static_pages#home'
    resources :users, only: [:show, :index, :destroy]
    resources :offsprings, only: [:new, :create, :destroy]
    resources :rooms, only: [:index]
    resources :assignments, only: [:new, :create, :destroy]
    resources :shifts, only: [:show]
    get 'admin' => 'admin#dashboard'
    post 'switch_lock_admin"' => 'admin#switch_lock_admin'
    get 'offsprings' => 'admin#offsprings'
    get 'users' => 'admin#users'
  end

end

app/models/offspring.rb
#
# Offsprings are related to a user and only one user.
# They can have one shift assingned
#
class Offspring < ActiveRecord::Base
  enum grade: %i(primary_first primary_second primary_third others)
  belongs_to :user
  belongs_to :shift
  validates :first_name, presence: true, length: { within: 3..60 }
  validates :last_name, presence: true, length: { within: 3..60 }
  validates :grade, presence: true
  validates :user, presence: true
  validates_each :shift, allow_nil: true do |offspring|
    offspring.errors.add(:shift, :no_space, message: "no hay espacio") unless offspring.shift.sites_available?
  end
  validates_each :last_name do |offspring|
    if offspring.user && offspring.user.offsprings.first
      unless offspring.last_name == offspring.user.offsprings.first.last_name
        offspring.errors.add(:last_name, :last_name, message: "tiene que coincidir con el de sus hermanos")
      end
    end
  end
end

app/controllers/offsprings_controller.rb
# Offsprings are dependent on users and are the ones that get assigned to shifts
# They can't be assigned themselves, and need the process to be done by the user
class OffspringsController < ApplicationController
  SCOPE = "activerecord.errors.controllers.offspring".freeze
  def show
  end

  def index
  end

  def new
    @offspring = current_user.offsprings.build
  end

  def create
    if access_control?
      @offspring = current_user.offsprings.build(offsprings_params)
      unless @offspring.primary_first?
        flash[:warning] = "Sólo puede añadir a niños de 1º de Primaria"
        redirect_to static_pages_intructions_path
        return
      end
      save_offspring(@offspring)
    else
      flash[:alert] = I18n.t("admin_locked_create", scope: SCOPE)
    end
    redirect_to root_path
  end

  def destroy
    if access_control?
      offspring = Offspring.find_by_id(params[:id])
      offspring.destroy
      flash[:success] = "Niño borrado"
    else
      flash[:alert] = I18n.t("admin_locked_destroy", scope: SCOPE)
    end
    redirect_to request.referer || root_url
  end

  private

  def offsprings_params
    params.require(:offspring).permit(:first_name, :last_name, :grade)
  end

  def save_offspring(off)
    if off.save
      flash[:success] = "Niño añadido"
    else
      flash[:danger] = "No se pudo añadir al niño"
    end
  end

  def access_control?
    !ApplicationHelper.status_lock?
  end
end

app/helpers/offsprings_helper.rb
module OffspringsHelper
  include Devise::Controllers::Helpers
end

app/views/offsprings/_offspring.html.erb
<tr>
  <td>
    <%= offspring.first_name %>
  </td>
  <td>
    <%= offspring.last_name %>
  </td>
  <td>
    <%= I18n.t offspring.grade %>
  </td>
  <td>
    <%= link_to full_name_for(offspring.user),offspring.user %>
  </td>
  <td>
    <% if offspring.shift.nil? %>
      <%= link_to "Asignar horario", new_assignment_path(offspring), class: "btn btn-warning"%>
    <% else %>
      <%= button_to "#{week_day_convert(offspring.shift.day_of_week)}: #{offspring.shift.start_time}", assignment_path(offspring), method: :delete, data: { confirm: 'Esto borrará la asignación y comenzará una nueva, ¿Está seguro?'}, class: "btn btn-success" %>
    <% end %>
    <%= button_to "Borrar niño", { action: "destroy", controller: 'offsprings', id: offspring.id} , method: :delete, data: { confirm: 'Esta acción no puede cancelarse, ¿Está seguro?'} , class:"btn btn-primary"%>
  </td>
</tr>

app/views/offsprings/index.html.erb
<% provide(:title, 'Lista de catecúmenos') %>
<h1>Índice de catecúmenos</h1>

<table class="datatable table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Curso</th>
      <th>Padre</th>
    </tr>
  </thead>
  <tbody>
      <%= render @offsprings %>
  </tbody>
</table>

<script>
  // Initialize Datatables
  $(document).ready(function() {
    $('.datatable').dataTable();
  });
</script>

app/views/offsprings/new.html.erb
<% provide(:title, 'Nuevo Hijo') %>
<h1>
  <%= "Añadir hijo de #{current_user.first_name} #{current_user.last_name}:" %>
</h1>

<div class="container">
  <%= form_for @offspring do |f| %>
    <form class="form-horizontal">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :grade %>
        <%= f.select :grade, Offspring.grades.map { |w,y| [I18n.t(w), w] }, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit t(:create), class:"btn btn-primary btn-lg", data: { confirm: '¿Es Ud. el padre o tutor legal del niño?'}%>
      </div>

    </form>
<% end %>

</div>