config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/intructions'
  get 'help' => 'static_pages#help'
  get 'about'=>'static_pages#about'
  devise_for :users
  authenticate :user do
    root to: "static_pages#home"
    get 'home' => 'static_pages#home'
    resources :users, only: [:show, :index, :destroy]
    resources :offsprings, only: [:new, :create, :destroy]
    resources :rooms, only: [:index]
    resources :assignments, only: [:new, :create, :destroy]
    resources :shifts, only: [:show]
    get 'admin' => 'admin#dashboard'
    post 'switch_lock_admin"' => 'admin#switch_lock_admin'
    get 'offsprings' => 'admin#offsprings'
    get 'users' => 'admin#users'
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="<%= flash_class(message_type) + " alert-dismissable"%>">
        <button type="button" class="close" data-dismiss="alert" area-hidden="true">
      <span class="pficon pficon-close"></span>
    </button>
    <span class="<%=flash_icon(message_type)%>"></span>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="row">
<%= link_to image_tag("logo.png", alt: "Parroquia de las tablas", class:"img-responsive"),
            'http://www.archimadrid.es/lastablas/' %>
</nav>
<nav class="navbar navbar-default navbar-pf" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      Parroquia de las Tablas
    </a>
  </div>
  <div class="collapse navbar-collapse navbar-collapse-1">
    <ul class="nav navbar-nav navbar-utility">
      <% if !signed_in? %>
      <li>
        <%= link_to "Entrar", new_user_session_path %>
      </li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span class="pficon pficon-user"></span>
          <% if !!current_user %>
          <%= current_user.first_name %><b class="fa fa-angle-down"> </b>
          <% else %>
          <%= "Entrar " %><b class="fa fa-angle-down"> </b>

          <% end %>
        </a>

        <ul class="dropdown-menu">
          <li>
            <%= link_to " Principal ", home_path, class:"pficon pficon-home" %>
          </li>
          <li class="divider">
          </li>
          <li>

            <%= link_to " Ayuda ", help_path, class:"pficon pficon-help" %>
          </li>
          <li class="divider"></li>
          <li>
          <%= link_to "Acerca de",about_path %>
          </li>
          <% if signed_in? %>
            <li>
              <%= link_to "Editar perfil",  edit_user_registration_path(current_user) %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to " Salir ", destroy_user_session_path, method: :delete, class:"fa fa-power-off" %>
            </li>

          <% end %>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-primary">
      <%if url_for==root_path %>
        <li class="active">
      <% else %>
        <li>
      <%end%>
        <%= link_to "Principal",root_path %>
      </li>
      <% if url_for== edit_user_registration_path %>
        <li class="active">
      <% else %>
        <li>
      <% end %>
        <%= link_to "Editar",edit_user_registration_path(current_user) %>
      </li>
      <% if url_for==rooms_path %>
        <li class="active">
      <% else %>
        <li>
      <% end %>
        <%= link_to "Horarios", rooms_path %>
      </li>
      <%if url_for==help_path %>
        <li class="active">
      <% else %>
        <li>
      <%end%>
        <%= link_to "Ayuda",help_path %>
      </li>
      <% if current_user.try(:admin?) %>
      <li role="admin" class="dropdown">

        <%if url_for==admin_path %>

          <li class="active">
        <% else %>
          <li>
        <% end %>
            <%= link_to "Admin", admin_path %>
      </li>
      <% end %>
      <li>
        <%if url_for==about_path %>
          <li class="active">
        <% else %>
            <li>
              <% end %>
        <%= link_to "Acerca de",about_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

app/views/layouts/_show.html.erb
<h1>
<div>
  <div class="container-fluid">
    <lu class="list-group">
      <li class="img-thumbnail"><%= gravatar_for @user %> </li>
      <li class="list-group-item"><%= @user.first_name %></li>
      <li class="list-group-item"><%= @user.last_name %></li>
      <li class="list-group-item"><%= @user.email%></li>
      <li class="list-group-item"><%= @user.phone%></li>
    </lu>
  </div>
  <div class="list-group">
  <% if @user.offsprings.any? %>
      <h3>Niños: (<%= @user.offsprings.count %>)</h3>
      <div class="list-group list-view-pf">
        <%= render @user.offsprings %>
      </div>
    <% end %>
  </div>

  <div class="container-fluid">
    <%= link_to "Añadir niño", new_offspring_path  %>
  </div>
</div>


<script>
  // Row Checkbox Selection
  $(document).ready(function () {
    $("input[type='checkbox']").change(function (e) {
      if ($(this).is(":checked")) {
        $(this).closest('.list-group-item').addClass("active");
      } else {
        $(this).closest('.list-group-item').removeClass("active");
      }
    });
  });
<script>

app/views/layouts/admin.html.erb
<%= render template: "layouts/application" %>
<%= render "admin/principal" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 9]><html class="ie9"><![endif]-->
<!--[if gt IE 9]><!-->
<html lang="es">
<!--<![endif]-->
  <head>
    <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title><%=full_title(yield(:title))%></title>

    <%= render 'layouts/shim' %>

</head>
  <body>
    <%= render 'layouts/header' %>
     
    <%= render 'layouts/flash' %>

    <div class="container-fluid">
      <%= yield %>
    </div>
    <div class="well-lg">
       <%= debug(params) if Rails.env.development? %>
   </div>
  </body>
</html>